language: python
dist: xenial
python:
- 3.7
install:
- pip install -r requirements.txt --upgrade
- pip install -r test_requirements.txt --upgrade
- pip install -e .
script:
- pycodestyle
- pytest
deploy:
  provider: pypi
  username:
    secure: wnQjcv6tEod0UXUDO7ZLiFm8qsVu8PEWD07qdFn0xJjI5L5lP0PzhhhINzbdkHrfiLixU0UnuTbxLqrvfSiZjjY0V9MJtWb/JWBWNIcomCRjSSRJpFmRG4Ix+0kcIAxFcXwUm6Of5C3+NfZxbFW9O2JuOU7lSoM1INUFMORPEm/OAPXzMmbzRNDqWk29tEvce4JwzIPqlGiG5FN/i35Sf33v3UBU6mS0APKnACxddN+8wxHriFcGZhwHuTY6+DcP6ddmn8boBLJIGVgOp7Mg4ndGrDjpyuUhbdcmIXbq2eg6LZ/ySwodu509oCDjTTBmjz6v+xzRDfKUx0F2J7hIf1l4ngr/Am1Xbr83fxBwznga8gJrBqGjZCJzyPRFX7XMQEtHoJeMbaPSCuon+y/S/1XumtTJJmfk+k6s+3ka3VAEOe+Nx0ndYJysAjzCPaMeVkFsn1UDyxGm2Zcw/aabboAppnuSDfBiKRff5vyXnueAAs50i38vwS89EZbv5cuUXGnhYdtCqsIocwjul31wYbXQiiw7FsGLsJxJeofO/dRaeLZSzig3nYc7RfwTYG7JtBxTqrbP6SpRFx6Y55cIGLgu/NiCv+NnMErXBuwy5uHIhr061bQO5e8E/Y6rHlp4beJmNFMP8nZ9wAaYwzdteoxQBy3sqSWY5EB4uBlltd0=
  password:
    secure: qSyzBarbyjoA2BidCHQy4/jILBCxnoA6LHiRhN/2ap1uuJIwU/Fb4Zx/k3qPXy6lpEZ88XZF1T3F+Ee1SZAJHPEfA+cfDvo0Q+y3JImwjT5UWCiVVKmUov9BIlD4V4ppe71ILs0iZB5XV5J+bsG6G4oM1xcmIGL5mD+aBwtvhHvdOpTpuyK+KhYJdNsKD9e99n/0l6/z5yLy5pAnEwXOe3fkejRVyC6UXiPLGLDL39/DSm98tuXl8nuiGuFqFzn99vIqy9F6ItcyEqm+cNfv46EH2+HoPo1/4cEAPRRLNgcrYNEgHA39wHnLxxPWIV1+bwNrVwLcWPxBOmkVy3kxS/HonFtHIBs33tItU2iaAfCar29iXsXwJnW5t07Okcda7oQSg14/yGkLK0XMDFEZUW+cQrC6UGsO93FogTSYJOYDtbTU0m5msc8hpZWgcesB984xWqefWglTfvId9W7U+8LdIbVQzIcNrAVh9yQOFT93J63ucODFSvq3bl5b5JUweSTnJSSN7SxvcrljECEXgxSzujz+XCPsW1dMPd1k1EYgMKMkTyvcI9CS0Xdc2DcSvhC5R030xmjTm78PNK+p5L3hWS85ITQH3dUJip12yZbQ3TwIJhYdRYEYXZdXGvQ4v8k6g/58IUoVTR1eDv+OF98bKyajmmF4UAS4o9XM6Dg=
  on:
    tags: true
    branch: master
    python: 3.7
  distributions: sdist bdist_wheel
notifications:
  email:
    on_success: never
