language: python
dist: xenial
python:
  - 3.7

install:
  - pip install -r requirements.txt --upgrade
  - pip install -r test_requirements.txt --upgrade
  - pip install -e .

script:
  - pycodestyle
  - pytest

deploy:
  provider: pypi
  username:
    secure: lSgaBotxbD8+zTHyqM+hFiUc1rnzCFPnEX7DqdBB8Abtza8RFI962be8bUzUxFVuoeX5PSbGLTMnEynk+UqFdK1mIfuXOHJHCbTpWsyG7ADN4IOV/0dzJbbgobsj2uau0UW6CHjN7v32W+hNmht2lKXm2nrVOgG2yQgqjWtrMxlyZFZaa8u2LtDA/NqNgLthIEzH9Gsmk0Gmog40AazV41k5orKqNc32kP3UxgZ6v7u5NSoXJDGk7P5M1kquG7wxAu1j56JtoBXpYZvJHb71qMFMRi4kIELpkGz0Z6IdGmINopJm/DmD+WOIdmWj+TKuyXc9i6GQHu+JXbQXaoWDqAAXNcuYCHGoja12/fMFqy5NoTRQsz3kCWT9bMResD36zGSVWrByZe0/8a8gGUW+9AvTZmMK7JgghZy8CtJgWXbQDkAOkByxatht8mUECr8MMonkL7TemQBMn81nNZ3j/zGW7IZXYPeKKItEozU6raU4ylSma4bi3csW76NL2YTpb5bNIGgVANjAkOPbqhws5ZQ61GlAcOntrBsu6eMM+J8pGhGYl+v+/hVlZwP1irXmR0/Ol2frivNRppQvxoGe9WPEGS8UwB8/lecVHqBGJmOa5b09Hk5qRTgPb/ye3OXnv6Sr+xoq2g739g5VXMTcY42UWQmIKQ5OWXnP5k60B3A=
  password:
    secure: tBiUsHS94Zrxg0mCuyWJtKbch6cK3IQA9FH9ex2LvWL0uAXKA76k3pqkTNIpQ4/Oj3AgBQaSC3Si8wOOcih7Wv149selPyvvJyautRYPPyQB2VfIbsiDfo70vnJh+ty7WnLtGEz9ww/yaBls5AubLtc6guXAYvrJOTE5byJ5kPkwt514HeEvGFvIjSDWNZMMoeQI2yvTGcwfBIMsAmDT1WUGaAD4T1gKoYqSm/oA3AXQDv+sL07O0g1OSyRrk9NU7fqVj7zfC81m7yvz/qBgkBFB28wsnbyOC/t108nqlIpBjzacaQLaEVgwP9NxYZwFsa85SNexp2xjqtL1EQkHJaRgrL86jIMRpRl6PnUoEeEMzGoXD+wty9Q/yhDLnfoLlg0OQ3+ITQkExNHEf8E9MzUxataK2BUl2r+x5jf5UPiFJC0z8VX/Es7RzOWs63DSrC0806vqbY8w1SHB3KKcxMHDYL+chweuNY+CDg1F9JxRp+WG8lBvImpGOanSO9b+uRf9lsO7dhbuYn6FckNMTtFPtOlvADSLudoJwpuPpLBc0r1uYdw9ELXCYb6ojg+OCWBCBXJC8X2HLYWTHquNauJtaYIbri2PDtoycwVK4zBGcsPxRWMo2XJteEKVZod2lTPvod5QPBpvsxfvJTrg2MURDDQtCo7BvnJSZ1F5xcw=
  on:
    tags: true
    branch: master
    python: 3.7
  distributions: "sdist bdist_wheel"

notifications:
  email:
    on_success: never
